# coding: utf-8

"""
    GTFS Garage API

    The contract between a GTFS Garage viewer and whatever feeds it.  This document is the source of truth. The server's pydantic models and the viewer's TypeScript types are both generated from it.  A host embedding `gtfs-garage-web` has three options, and only the second needs this document in full:  1. Point the viewer at a GTFS Garage server, which implements everything here. 2. Implement these endpoints on your own backend. The viewer's `RestSource`    then drives it unchanged. 3. Implement the browser-side `ViewerSource` interface instead, which is not    an HTTP contract and is described in `docs/INTEGRATION.md`.  Two things this document deliberately does not settle, because they are the host's to decide and a GTFS Garage server needs neither:  - **CORS.** A GTFS Garage server serves the viewer from its own origin and   adds no CORS middleware. A host serving these endpoints to a page on   another origin must send the usual headers itself. - **Authentication.** `RestSource` sets no request header and no   `credentials` option, so a same-origin session cookie is sent by   `fetch`'s own default and nothing else is. A bearer token, or a cookie on   a cross-origin request, cannot be reached by pointing `baseUrl` at the   backend; implement `ViewerSource` instead.  See `docs/INTEGRATION.md` for embedding the viewer, and the `DatasetManifest` schema below for the Parquet layout a static host serves. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from gtfs_garage_gen.models.condition_outcome import ConditionOutcome
from gtfs_garage_gen.models.implied_value import ImpliedValue
from gtfs_garage_gen.models.related_link import RelatedLink
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ColumnInfo(BaseModel):
    """
    One column, with everything GTFS says about the field it holds. The viewer formats values, offers picklists and draws foreign keys as links from this alone, so a host supplying its own columns decides how much of the schema the interface can show.
    """ # noqa: E501
    name: StrictStr
    fk_table: Optional[StrictStr] = Field(default=None, description="Set only when the referenced table and column exist in **this** feed. Most GTFS files are optional, so a link is never offered to a file the feed does not have.")
    fk_column: Optional[StrictStr] = None
    enum_like: Optional[StrictBool] = Field(default=False, description="GTFS defines a small fixed value set for this column, so the filter builder offers the values actually present with their counts.")
    related: Optional[List[RelatedLink]] = Field(default=None, description="Tables pointing back at this column, offered as the reverse direction - from a route straight to the trips that use it. Always present; empty unless this column is its table's primary id.")
    type: Optional[StrictStr] = Field(default=None, description="What GTFS says the field holds - `ID`, `ENUM`, `COLOR`, `LATITUDE`, `DATE` and so on. Null for a column the schema does not describe, such as a producer's own extension, which renders as text.")
    values: Optional[Dict[str, StrictStr]] = Field(default=None, description="For an enumeration, its codes and their labels; null otherwise.")
    required: Optional[StrictStr] = Field(default=None, description="Null where GTFS makes the field optional.")
    condition: Optional[StrictStr] = Field(default=None, description="For a conditionally required field, the condition in words. Null otherwise.")
    condition_scope: Optional[StrictStr] = Field(default=None, description="What settles the condition. `row` where the row does, `feed` where the feed as a whole does - and then `condition_outcome` carries the answer - and `row_context` where it varies row by row on something the row does not carry. Null unless the field is conditional.")
    condition_outcome: Optional[ConditionOutcome] = None
    when_empty: Optional[ImpliedValue] = None
    pattern: Optional[StrictStr] = Field(default=None, description="What a value of this field's type must look like. Applied by the viewer before any formatting, compiled once and cached - a feed can have sixty million rows - and skipped rather than thrown if it will not compile, because no value may ever be blanked. Must mean the same thing in Python and JavaScript.")
    minimum: Optional[Union[StrictFloat, StrictInt]] = None
    maximum: Optional[Union[StrictFloat, StrictInt]] = None
    type_description: Optional[StrictStr] = Field(default=None, description="GTFS's own definition of the type, for when a value does not match it.")
    __properties: ClassVar[List[str]] = ["name", "fk_table", "fk_column", "enum_like", "related", "type", "values", "required", "condition", "condition_scope", "condition_outcome", "when_empty", "pattern", "minimum", "maximum", "type_description"]

    @field_validator('required')
    def required_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('always', 'conditional'):
            raise ValueError("must be one of enum values ('always', 'conditional')")
        return value

    @field_validator('condition_scope')
    def condition_scope_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('row', 'feed', 'row_context'):
            raise ValueError("must be one of enum values ('row', 'feed', 'row_context')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ColumnInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in related (list)
        _items = []
        if self.related:
            for _item in self.related:
                if _item:
                    _items.append(_item.to_dict())
            _dict['related'] = _items
        # override the default output from pydantic by calling `to_dict()` of condition_outcome
        if self.condition_outcome:
            _dict['condition_outcome'] = self.condition_outcome.to_dict()
        # override the default output from pydantic by calling `to_dict()` of when_empty
        if self.when_empty:
            _dict['when_empty'] = self.when_empty.to_dict()
        # set to None if fk_table (nullable) is None
        # and model_fields_set contains the field
        if self.fk_table is None and "fk_table" in self.model_fields_set:
            _dict['fk_table'] = None

        # set to None if fk_column (nullable) is None
        # and model_fields_set contains the field
        if self.fk_column is None and "fk_column" in self.model_fields_set:
            _dict['fk_column'] = None

        # set to None if type (nullable) is None
        # and model_fields_set contains the field
        if self.type is None and "type" in self.model_fields_set:
            _dict['type'] = None

        # set to None if values (nullable) is None
        # and model_fields_set contains the field
        if self.values is None and "values" in self.model_fields_set:
            _dict['values'] = None

        # set to None if required (nullable) is None
        # and model_fields_set contains the field
        if self.required is None and "required" in self.model_fields_set:
            _dict['required'] = None

        # set to None if condition (nullable) is None
        # and model_fields_set contains the field
        if self.condition is None and "condition" in self.model_fields_set:
            _dict['condition'] = None

        # set to None if condition_scope (nullable) is None
        # and model_fields_set contains the field
        if self.condition_scope is None and "condition_scope" in self.model_fields_set:
            _dict['condition_scope'] = None

        # set to None if condition_outcome (nullable) is None
        # and model_fields_set contains the field
        if self.condition_outcome is None and "condition_outcome" in self.model_fields_set:
            _dict['condition_outcome'] = None

        # set to None if when_empty (nullable) is None
        # and model_fields_set contains the field
        if self.when_empty is None and "when_empty" in self.model_fields_set:
            _dict['when_empty'] = None

        # set to None if pattern (nullable) is None
        # and model_fields_set contains the field
        if self.pattern is None and "pattern" in self.model_fields_set:
            _dict['pattern'] = None

        # set to None if minimum (nullable) is None
        # and model_fields_set contains the field
        if self.minimum is None and "minimum" in self.model_fields_set:
            _dict['minimum'] = None

        # set to None if maximum (nullable) is None
        # and model_fields_set contains the field
        if self.maximum is None and "maximum" in self.model_fields_set:
            _dict['maximum'] = None

        # set to None if type_description (nullable) is None
        # and model_fields_set contains the field
        if self.type_description is None and "type_description" in self.model_fields_set:
            _dict['type_description'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ColumnInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "fk_table": obj.get("fk_table"),
            "fk_column": obj.get("fk_column"),
            "enum_like": obj.get("enum_like") if obj.get("enum_like") is not None else False,
            "related": [RelatedLink.from_dict(_item) for _item in obj.get("related")] if obj.get("related") is not None else None,
            "type": obj.get("type"),
            "values": obj.get("values"),
            "required": obj.get("required"),
            "condition": obj.get("condition"),
            "condition_scope": obj.get("condition_scope"),
            "condition_outcome": ConditionOutcome.from_dict(obj.get("condition_outcome")) if obj.get("condition_outcome") is not None else None,
            "when_empty": ImpliedValue.from_dict(obj.get("when_empty")) if obj.get("when_empty") is not None else None,
            "pattern": obj.get("pattern"),
            "minimum": obj.get("minimum"),
            "maximum": obj.get("maximum"),
            "type_description": obj.get("type_description")
        })
        return _obj


