# coding: utf-8

"""
    GTFS Garage API

    The contract between a GTFS Garage viewer and whatever feeds it.  This document is the source of truth. The server's pydantic models and the viewer's TypeScript types are both generated from it, so there is one description of the contract rather than two that agree by hand.  A host embedding `gtfs-garage-web` has three options, and only the second needs this document in full:  1. Point the viewer at a GTFS Garage server, which implements everything here. 2. Implement these endpoints on your own backend. The viewer's `RestSource`    then drives it unchanged. 3. Implement the browser-side `ViewerSource` interface instead, which is not    an HTTP contract and is described in `docs/INTEGRATION.md`.  Two things this document deliberately does not settle, because they are the host's to decide and a GTFS Garage server needs neither:  - **CORS.** A GTFS Garage server serves the viewer from its own origin and   adds no CORS middleware. A host serving these endpoints to a page on   another origin must send the usual headers itself. - **Authentication.** Nothing in `RestSource` sets a request header. A   backend behind a bearer token cannot be reached by pointing `baseUrl` at   it; implement `ViewerSource` instead.  See `docs/INTEGRATION.md` for embedding the viewer, and the `DatasetManifest` schema below for the Parquet layout a static host serves. 

    The version of the OpenAPI document: 1.0.0
    Contact: api@mobilitydata.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class FileMetrics(BaseModel):
    """
    What one file cost to open.
    """ # noqa: E501
    name: StrictStr
    table: StrictStr
    bytes: StrictInt = Field(description="Uncompressed size on disk.")
    compressed_bytes: Optional[StrictInt] = Field(default=None, description="Only for a zip source; a folder has no compressed form.")
    register_ms: Union[StrictFloat, StrictInt] = Field(description="Declaring the view, which resolves the column list off the start of the file and reads no further - so it barely varies with size. The interface labels it \"read headers\".")
    convert_ms: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Rewriting this table as Parquet; null when it was not converted.")
    parquet_bytes: Optional[StrictInt] = Field(default=None, description="What the table occupies once converted, typically far below `bytes`.")
    count_ms: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The row count. Near zero on Parquet, which carries it in the footer.")
    row_count: Optional[StrictInt] = None
    columns: StrictInt
    __properties: ClassVar[List[str]] = ["name", "table", "bytes", "compressed_bytes", "register_ms", "convert_ms", "parquet_bytes", "count_ms", "row_count", "columns"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FileMetrics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if compressed_bytes (nullable) is None
        # and model_fields_set contains the field
        if self.compressed_bytes is None and "compressed_bytes" in self.model_fields_set:
            _dict['compressed_bytes'] = None

        # set to None if convert_ms (nullable) is None
        # and model_fields_set contains the field
        if self.convert_ms is None and "convert_ms" in self.model_fields_set:
            _dict['convert_ms'] = None

        # set to None if parquet_bytes (nullable) is None
        # and model_fields_set contains the field
        if self.parquet_bytes is None and "parquet_bytes" in self.model_fields_set:
            _dict['parquet_bytes'] = None

        # set to None if count_ms (nullable) is None
        # and model_fields_set contains the field
        if self.count_ms is None and "count_ms" in self.model_fields_set:
            _dict['count_ms'] = None

        # set to None if row_count (nullable) is None
        # and model_fields_set contains the field
        if self.row_count is None and "row_count" in self.model_fields_set:
            _dict['row_count'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of FileMetrics from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "table": obj.get("table"),
            "bytes": obj.get("bytes"),
            "compressed_bytes": obj.get("compressed_bytes"),
            "register_ms": obj.get("register_ms"),
            "convert_ms": obj.get("convert_ms"),
            "parquet_bytes": obj.get("parquet_bytes"),
            "count_ms": obj.get("count_ms"),
            "row_count": obj.get("row_count"),
            "columns": obj.get("columns")
        })
        return _obj


