# coding: utf-8

"""
    GTFS Garage API

    The contract between a GTFS Garage viewer and whatever feeds it.  This document is the source of truth. The server's pydantic models and the viewer's TypeScript types are both generated from it, so there is one description of the contract rather than two that agree by hand.  A host embedding `gtfs-garage-web` has three options, and only the second needs this document in full:  1. Point the viewer at a GTFS Garage server, which implements everything here. 2. Implement these endpoints on your own backend. The viewer's `RestSource`    then drives it unchanged. 3. Implement the browser-side `ViewerSource` interface instead, which is not    an HTTP contract and is described in `docs/INTEGRATION.md`.  Two things this document deliberately does not settle, because they are the host's to decide and a GTFS Garage server needs neither:  - **CORS.** A GTFS Garage server serves the viewer from its own origin and   adds no CORS middleware. A host serving these endpoints to a page on   another origin must send the usual headers itself. - **Authentication.** Nothing in `RestSource` sets a request header. A   backend behind a bearer token cannot be reached by pointing `baseUrl` at   it; implement `ViewerSource` instead.  See `docs/INTEGRATION.md` for embedding the viewer, and the `DatasetManifest` schema below for the Parquet layout a static host serves. 

    The version of the OpenAPI document: 1.0.0
    Contact: api@mobilitydata.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class FilterOperator(str, Enum):
    """
    How a filter compares. The semantics are not obvious and a reimplementation that differs will look right and behave wrongly:  - `eq` / `ne` - equality. **An empty value is rewritten** to `is_empty` /   `is_not_empty`, because an empty field loads as NULL and `= ''` would   match nothing - which is how the \"(empty)\" picklist entry came to   report a count and return no rows. - `contains` - case-insensitive substring. - `in` - the value is a comma-separated list, trimmed, with empties   dropped. If nothing remains the filter is skipped entirely. - `is_empty` / `is_not_empty` - NULL **or** the empty string, both.  A filter naming a column the table does not have, or an operator not listed here, is ignored rather than refused. 
    """

    """
    allowed enum values
    """
    EQ = 'eq'
    NE = 'ne'
    CONTAINS = 'contains'
    IN = 'in'
    IS_EMPTY = 'is_empty'
    IS_NOT_EMPTY = 'is_not_empty'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FilterOperator from a JSON string"""
        return cls(json.loads(json_str))


