# coding: utf-8

"""
    GTFS Garage API

    The contract between a GTFS Garage viewer and whatever feeds it.  This document is the source of truth. The server's pydantic models and the viewer's TypeScript types are both generated from it, so there is one description of the contract rather than two that agree by hand.  A host embedding `gtfs-garage-web` has three options, and only the second needs this document in full:  1. Point the viewer at a GTFS Garage server, which implements everything here. 2. Implement these endpoints on your own backend. The viewer's `RestSource`    then drives it unchanged. 3. Implement the browser-side `ViewerSource` interface instead, which is not    an HTTP contract and is described in `docs/INTEGRATION.md`.  Two things this document deliberately does not settle, because they are the host's to decide and a GTFS Garage server needs neither:  - **CORS.** A GTFS Garage server serves the viewer from its own origin and   adds no CORS middleware. A host serving these endpoints to a page on   another origin must send the usual headers itself. - **Authentication.** Nothing in `RestSource` sets a request header. A   backend behind a bearer token cannot be reached by pointing `baseUrl` at   it; implement `ViewerSource` instead.  See `docs/INTEGRATION.md` for embedding the viewer, and the `DatasetManifest` schema below for the Parquet layout a static host serves. 

    The version of the OpenAPI document: 1.0.0
    Contact: api@mobilitydata.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from gtfs_garage_gen.models.file_metrics import FileMetrics
from gtfs_garage_gen.models.load_phase_timing import LoadPhaseTiming
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class LoadMetrics(BaseModel):
    """
    What the feed cost to open.  Two mutually exclusive shapes. A server load reports `kind` and the timings below it. A source that performed no server load - a browser reading Parquet over range requests never downloads, unzips or converts - reports `phases` instead and omits the rest. A zero would say the work took no time rather than that it did not happen, which is why the fields are absent rather than zeroed. 
    """ # noqa: E501
    phases: Optional[List[LoadPhaseTiming]] = Field(default=None, description="Phases this source actually performed. Present only for a source that is not a server load.")
    kind: Optional[StrictStr] = Field(default=None, description="How the feed reached the server. Absent for a non-server source.")
    acquire_ms: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Downloading or receiving the upload; null for a local path.")
    acquire_bytes: Optional[StrictInt] = None
    extract_ms: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Unzipping; null when the source was already-extracted files.")
    register_ms: Optional[Union[StrictFloat, StrictInt]] = None
    convert_ms: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Converting to Parquet; null when it was not converted.")
    count_ms: Optional[Union[StrictFloat, StrictInt]] = None
    total_ms: Union[StrictFloat, StrictInt] = Field(description="The phases added together.")
    total_bytes: StrictInt = Field(description="The archive's size, or the sum of the files in a folder.")
    stored_bytes: Optional[StrictInt] = Field(default=None, description="What the feed occupies to query once converted; null when it was not.")
    files: List[FileMetrics]
    __properties: ClassVar[List[str]] = ["phases", "kind", "acquire_ms", "acquire_bytes", "extract_ms", "register_ms", "convert_ms", "count_ms", "total_ms", "total_bytes", "stored_bytes", "files"]

    @field_validator('kind')
    def kind_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('path', 'upload', 'folder', 'download'):
            raise ValueError("must be one of enum values ('path', 'upload', 'folder', 'download')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of LoadMetrics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in phases (list)
        _items = []
        if self.phases:
            for _item in self.phases:
                if _item:
                    _items.append(_item.to_dict())
            _dict['phases'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in files (list)
        _items = []
        if self.files:
            for _item in self.files:
                if _item:
                    _items.append(_item.to_dict())
            _dict['files'] = _items
        # set to None if acquire_ms (nullable) is None
        # and model_fields_set contains the field
        if self.acquire_ms is None and "acquire_ms" in self.model_fields_set:
            _dict['acquire_ms'] = None

        # set to None if acquire_bytes (nullable) is None
        # and model_fields_set contains the field
        if self.acquire_bytes is None and "acquire_bytes" in self.model_fields_set:
            _dict['acquire_bytes'] = None

        # set to None if extract_ms (nullable) is None
        # and model_fields_set contains the field
        if self.extract_ms is None and "extract_ms" in self.model_fields_set:
            _dict['extract_ms'] = None

        # set to None if convert_ms (nullable) is None
        # and model_fields_set contains the field
        if self.convert_ms is None and "convert_ms" in self.model_fields_set:
            _dict['convert_ms'] = None

        # set to None if stored_bytes (nullable) is None
        # and model_fields_set contains the field
        if self.stored_bytes is None and "stored_bytes" in self.model_fields_set:
            _dict['stored_bytes'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of LoadMetrics from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "phases": [LoadPhaseTiming.from_dict(_item) for _item in obj.get("phases")] if obj.get("phases") is not None else None,
            "kind": obj.get("kind"),
            "acquire_ms": obj.get("acquire_ms"),
            "acquire_bytes": obj.get("acquire_bytes"),
            "extract_ms": obj.get("extract_ms"),
            "register_ms": obj.get("register_ms"),
            "convert_ms": obj.get("convert_ms"),
            "count_ms": obj.get("count_ms"),
            "total_ms": obj.get("total_ms"),
            "total_bytes": obj.get("total_bytes"),
            "stored_bytes": obj.get("stored_bytes"),
            "files": [FileMetrics.from_dict(_item) for _item in obj.get("files")] if obj.get("files") is not None else None
        })
        return _obj


