# coding: utf-8

"""
    GTFS Garage API

    The contract between a GTFS Garage viewer and whatever feeds it.  This document is the source of truth. The server's pydantic models and the viewer's TypeScript types are both generated from it.  A host embedding `gtfs-garage-web` has three options, and only the second needs this document in full:  1. Point the viewer at a GTFS Garage server, which implements everything here. 2. Implement these endpoints on your own backend. The viewer's `RestSource`    then drives it unchanged. 3. Implement the browser-side `ViewerSource` interface instead, which is not    an HTTP contract and is described in `docs/INTEGRATION.md`.  Two things this document deliberately does not settle, because they are the host's to decide and a GTFS Garage server needs neither:  - **CORS.** A GTFS Garage server serves the viewer from its own origin and   adds no CORS middleware. A host serving these endpoints to a page on   another origin must send the usual headers itself. - **Authentication.** `RestSource` sets no request header and no   `credentials` option, so a same-origin session cookie is sent by   `fetch`'s own default and nothing else is. A bearer token, or a cookie on   a cross-origin request, cannot be reached by pointing `baseUrl` at the   backend; implement `ViewerSource` instead.  See `docs/INTEGRATION.md` for embedding the viewer, and the `DatasetManifest` schema below for the Parquet layout a static host serves. 

    The version of the OpenAPI document: 1.0.0
    Contact: api@mobilitydata.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401



from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from gtfs_garage_gen.models.ndjson_batch import NdjsonBatch
from gtfs_garage_gen.models.ndjson_header import NdjsonHeader
from typing import Union, Any, List, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal
from pydantic import StrictStr, Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

NDJSONLINE_ONE_OF_SCHEMAS = ["NdjsonBatch", "NdjsonHeader"]

class NdjsonLine(BaseModel):
    """
    One line of an `application/x-ndjson` layer stream: a header, then any number of batches, each a complete JSON document followed by `\\n`.  A whole layer is far too large to wait for in one piece - a large feed is about 411 MB of GeoJSON - so it is sent as it is read and the map paints as it arrives. A reader must buffer across chunk boundaries, which fall wherever the network puts them and almost never on a newline, and should skip a line that will not parse rather than abandoning the layer. 
    """
    # data type: NdjsonHeader
    oneof_schema_1_validator: Optional[NdjsonHeader] = None
    # data type: NdjsonBatch
    oneof_schema_2_validator: Optional[NdjsonBatch] = None
    actual_instance: Optional[Union[NdjsonBatch, NdjsonHeader]] = None
    one_of_schemas: List[str] = Literal["NdjsonBatch", "NdjsonHeader"]

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = NdjsonLine.model_construct()
        error_messages = []
        match = 0
        # validate data type: NdjsonHeader
        if not isinstance(v, NdjsonHeader):
            error_messages.append(f"Error! Input type `{type(v)}` is not `NdjsonHeader`")
        else:
            match += 1
        # validate data type: NdjsonBatch
        if not isinstance(v, NdjsonBatch):
            error_messages.append(f"Error! Input type `{type(v)}` is not `NdjsonBatch`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in NdjsonLine with oneOf schemas: NdjsonBatch, NdjsonHeader. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in NdjsonLine with oneOf schemas: NdjsonBatch, NdjsonHeader. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: dict) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into NdjsonHeader
        try:
            instance.actual_instance = NdjsonHeader.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into NdjsonBatch
        try:
            instance.actual_instance = NdjsonBatch.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into NdjsonLine with oneOf schemas: NdjsonBatch, NdjsonHeader. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into NdjsonLine with oneOf schemas: NdjsonBatch, NdjsonHeader. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        to_dict = getattr(self.actual_instance, "to_dict", None)
        if callable(to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


