# coding: utf-8

"""
    GTFS Garage API

    The contract between a GTFS Garage viewer and whatever feeds it.  This document is the source of truth. The server's pydantic models and the viewer's TypeScript types are both generated from it, so there is one description of the contract rather than two that agree by hand.  A host embedding `gtfs-garage-web` has three options, and only the second needs this document in full:  1. Point the viewer at a GTFS Garage server, which implements everything here. 2. Implement these endpoints on your own backend. The viewer's `RestSource`    then drives it unchanged. 3. Implement the browser-side `ViewerSource` interface instead, which is not    an HTTP contract and is described in `docs/INTEGRATION.md`.  Two things this document deliberately does not settle, because they are the host's to decide and a GTFS Garage server needs neither:  - **CORS.** A GTFS Garage server serves the viewer from its own origin and   adds no CORS middleware. A host serving these endpoints to a page on   another origin must send the usual headers itself. - **Authentication.** Nothing in `RestSource` sets a request header. A   backend behind a bearer token cannot be reached by pointing `baseUrl` at   it; implement `ViewerSource` instead.  See `docs/INTEGRATION.md` for embedding the viewer, and the `DatasetManifest` schema below for the Parquet layout a static host serves. 

    The version of the OpenAPI document: 1.0.0
    Contact: api@mobilitydata.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from gtfs_garage_gen.models.load_metrics import LoadMetrics
from gtfs_garage_gen.models.missing_file import MissingFile
from gtfs_garage_gen.models.table_info import TableInfo
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class TablesResponse(BaseModel):
    """
    TablesResponse
    """ # noqa: E501
    source: StrictStr = Field(description="What to call this feed in the header.")
    tables: List[TableInfo]
    missing: Optional[List[MissingFile]] = Field(default=None, description="Files absent from this feed that GTFS says it needs. Empty for a complete feed, which is the usual case.")
    metrics: Optional[LoadMetrics] = None
    __properties: ClassVar[List[str]] = ["source", "tables", "missing", "metrics"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TablesResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in tables (list)
        _items = []
        if self.tables:
            for _item in self.tables:
                if _item:
                    _items.append(_item.to_dict())
            _dict['tables'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in missing (list)
        _items = []
        if self.missing:
            for _item in self.missing:
                if _item:
                    _items.append(_item.to_dict())
            _dict['missing'] = _items
        # override the default output from pydantic by calling `to_dict()` of metrics
        if self.metrics:
            _dict['metrics'] = self.metrics.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of TablesResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "source": obj.get("source"),
            "tables": [TableInfo.from_dict(_item) for _item in obj.get("tables")] if obj.get("tables") is not None else None,
            "missing": [MissingFile.from_dict(_item) for _item in obj.get("missing")] if obj.get("missing") is not None else None,
            "metrics": LoadMetrics.from_dict(obj.get("metrics")) if obj.get("metrics") is not None else None
        })
        return _obj


