/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Settings the interface reads at startup
         * @description Read once before the viewer draws, so that a basemap chosen server-side reaches the page. A host that passes its own `basemap` never calls this, which is why the viewer treats a failure here as "no preference" rather than an error.
         */
        get: operations["getConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What the loaded feed contains
         * @description Every table with its row count and its columns, the files GTFS says are missing, and what the load cost. This is the viewer's first request and the one that populates the sidebar.
         */
        get: operations["getTables"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/table/{table}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The table name, which is the GTFS file stem - `stops` for `stops.txt`. `locations` is the flattened form of `locations.geojson`.
                 * @example stop_times
                 */
                table: components["parameters"]["table_path_param"];
            };
            cookie?: never;
        };
        /**
         * One page of a table
         * @description Rows matching the filters, one page at a time. `total` counts every matching row, not the page, so the viewer can draw the pager without a second request.
         */
        get: operations["getTable"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/table/{table}/distinct/{column}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The table name, which is the GTFS file stem - `stops` for `stops.txt`. `locations` is the flattened form of `locations.geojson`.
                 * @example stop_times
                 */
                table: components["parameters"]["table_path_param"];
                /**
                 * @description The column to count values of.
                 * @example route_type
                 */
                column: string;
            };
            cookie?: never;
        };
        /**
         * The values a column actually holds, with counts
         * @description What fills the picklist the filter builder offers for an enumerated column. Ordered by count, descending, so the common values come first.
         */
        get: operations["getDistinctValues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geojson/stops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stops, as points
         * @description With `stop_ids`, the named stops as one document, which is how the viewer highlights a row. Without, the whole layer as a stream. Stops are never thinned at any feed size: a stop is one point, so half a million of them cost far less than the lines do.
         */
        get: operations["getStopsGeojson"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geojson/shapes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Shapes, as lines
         * @description With `shape_ids`, the named shapes as one document. Without, every shape the routes layer does not already draw, as a stream. Highlighting a route goes through this path too, with the route's representative `shape_id`.
         */
        get: operations["getShapesGeojson"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geojson/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A flex feed's on-demand zones, as polygons
         * @description Drawn from the feed's own `locations.geojson`, whose geometry is passed through verbatim. A feed without that file streams a `total` of 0 and draws nothing, exactly as a feed without `shapes.txt` already does.
         */
        get: operations["getLocationsGeojson"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geojson/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One representative line per route, coloured by the feed
         * @description Streamed only - there is no id-filtered form, because a route is highlighted through its shape on `/api/geojson/shapes`. Each feature carries the route's own `route_color`, defaulting to `3388ff`.
         */
        get: operations["getRoutesGeojson"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/load/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Where a running load has got to
         * @description Safe to poll, and answered even when nothing is loading - `running` is then false. The viewer polls this while a feed opens so it can say "Converting stop_times (12 of 32)" rather than showing a blank page.
         */
        get: operations["getLoadProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open a feed
         * @description Implemented by a GTFS Garage server, which browses whatever feed you hand
         *     it. **A host embedding the viewer normally does not implement this**: an
         *     embedded viewer is built without the load dialog, so nothing calls it.
         *
         *     Exactly one source is used, in this order of precedence: uploaded
         *     `files`, an uploaded `file`, `url`, then `path`. A download is capped at
         *     2 GiB and 60 seconds, and only `http`/`https` are accepted.
         *
         *     Replacing the loaded feed does not disturb requests already in flight
         *     against the previous one; it is released when its last reader finishes.
         */
        post: operations["loadFeed"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What the server has written to disk
         * @description The workdir's path, whether it survives the process, how many feeds it keeps, and a row per feed it holds. The totals are measured from the directory rather than remembered, so they describe what is actually there.
         */
        get: operations["getWorkspace"];
        put?: never;
        post?: never;
        /**
         * Empty the workdir
         * @description Removes every feed whose files are not open. The feed being served is never removed - its Parquet is what every query reads - so emptying a workdir while browsing leaves exactly that one behind.
         */
        delete: operations["clearWorkspace"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace/feeds/{feed_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description A feed's id in the workdir, as `GET /api/workspace` reports it.
                 * @example montreal-gtfs-zip-7f3a91c0
                 */
                feed_id: components["parameters"]["feed_id_path_param"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete one feed's files
         * @description Refused with 409 while that feed is the one being served, or while a request is still reading it.
         */
        delete: operations["removeWorkspaceFeed"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace/feeds/{feed_id}/reload": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description A feed's id in the workdir, as `GET /api/workspace` reports it.
                 * @example montreal-gtfs-zip-7f3a91c0
                 */
                feed_id: components["parameters"]["feed_id_path_param"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Serve a feed the workdir already holds
         * @description Reopens the feed from the Parquet it was converted to at its first load, so there is nothing to download, unzip or convert. Replacing the loaded feed behaves exactly as `POST /api/load` does, in-flight requests included.
         */
        post: operations["reloadWorkspaceFeed"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Every error. The viewer reads `detail` and nothing else, and shows it to the user, so it should say what went wrong in words a reader can act on. */
        Error: {
            /** @example No GTFS feed loaded yet. */
            detail: string;
        };
        /** @description Settings the interface reads at startup. */
        ConfigResponse: {
            /**
             * @description A preset name (`openfreemap`, `esri`, `osm`, `carto`, `none`), a raster tile template containing `{z}/{x}/{y}`, or a vector style URL. The viewer resolves it.
             * @example openfreemap
             */
            basemap: string;
            /**
             * @description The version of GTFS Garage serving this API.
             * @example 1.4.2
             */
            version: string;
            /**
             * @description Whether this server manages a workdir and so answers the `workspace` paths. Absent or false means it does not, and the viewer builds no interface for one.
             * @example true
             */
            workspace?: boolean;
        };
        /** @description One feed the workdir holds. */
        WorkspaceFeed: {
            /**
             * @description The directory the feed occupies, derived from its label so that loading the same feed twice reuses one slot rather than two.
             * @example montreal-gtfs-zip-7f3a91c0
             */
            id: string;
            /**
             * @description What the feed was loaded as - a filename, a path, or a URL.
             * @example montreal-gtfs.zip
             */
            label: string;
            /**
             * @description How it was obtained.
             * @enum {string}
             */
            kind?: "path" | "upload" | "folder" | "download";
            /**
             * Format: date-time
             * @description When it was last loaded.
             */
            loaded_at?: string;
            /**
             * Format: int64
             * @description What the feed occupies in the workdir, measured from disk.
             */
            bytes: number;
            /** @description How many tables it holds. */
            tables: number;
            /** @description Whether there is Parquet to reopen it from. False for a feed loaded with `--no-parquet`, and for a load that did not finish. */
            reloadable: boolean;
            /** @description Whether this is the feed being served. */
            current: boolean;
        };
        /** @description The directory a GTFS Garage server writes into. */
        WorkspaceResponse: {
            /**
             * @description The workdir's absolute path on the server's filesystem.
             * @example /Users/sam/gtfs-work
             */
            path: string;
            /** @description Whether it survives the process. True when the server was started with `--workdir`; false for the per-run directory used otherwise, which is removed on exit. */
            persistent: boolean;
            /**
             * @description How many feeds are kept before the oldest is dropped. 0 means none are ever dropped.
             * @example 3
             */
            keep: number;
            /**
             * Format: int64
             * @description What the whole workdir occupies.
             */
            total_bytes: number;
            /** @description The feeds it holds, most recently loaded first. */
            feeds: components["schemas"]["WorkspaceFeed"][];
        };
        /** @description A table that points back at the current row's id. */
        RelatedLink: {
            /** @example trips */
            table: string;
            /** @example route_id */
            column: string;
        };
        /** @description What GTFS says an empty value means for this field. The viewer draws the implied value muted and italic, and hides it under the raw-values toggle, because raw means the characters the file holds and here it holds none. */
        ImpliedValue: {
            /**
             * @description One of the field's own enum codes. Null where the implied meaning has no code, as for `fare_attributes.transfers`, whose empty value means unlimited transfers.
             * @example 0
             */
            code?: string | null;
            /** @example Regularly scheduled pickup */
            label: string;
        };
        /** @description Whether a feed-scope condition holds in the feed now loaded. `evidence` is what the check counted to decide, so the answer can be read back rather than trusted. */
        ConditionOutcome: {
            holds: boolean;
            /** @example agency.txt has 3 rows */
            evidence: string;
        };
        /** @description One column, with everything GTFS says about the field it holds. The viewer formats values, offers picklists and draws foreign keys as links from this alone, so a host supplying its own columns decides how much of the schema the interface can show. */
        ColumnInfo: {
            /** @example route_id */
            name: string;
            /**
             * @description Set only when the referenced table and column exist in **this** feed. Most GTFS files are optional, so a link is never offered to a file the feed does not have.
             * @example routes
             */
            fk_table?: string | null;
            /** @example route_id */
            fk_column?: string | null;
            /**
             * @description GTFS defines a small fixed value set for this column, so the filter builder offers the values actually present with their counts.
             * @default false
             */
            enum_like: boolean;
            /**
             * @description Tables pointing back at this column, offered as the reverse direction - from a route straight to the trips that use it. Always present; empty unless this column is its table's primary id.
             * @default []
             */
            related: components["schemas"]["RelatedLink"][];
            /**
             * @description What GTFS says the field holds - `ID`, `ENUM`, `COLOR`, `LATITUDE`, `DATE` and so on. Null for a column the schema does not describe, such as a producer's own extension, which renders as text.
             * @example ID
             */
            type?: string | null;
            /** @description For an enumeration, its codes and their labels; null otherwise. */
            values?: {
                [key: string]: string;
            } | null;
            /**
             * @description Null where GTFS makes the field optional.
             * @enum {string|null}
             */
            required?: "always" | "conditional" | null;
            /**
             * @description For a conditionally required field, the condition in words. Null otherwise.
             * @example Required if route_long_name is empty.
             */
            condition?: string | null;
            /**
             * @description What settles the condition. `row` where the row does, `feed` where the feed as a whole does - and then `condition_outcome` carries the answer - and `row_context` where it varies row by row on something the row does not carry. Null unless the field is conditional.
             * @enum {string|null}
             */
            condition_scope?: "row" | "feed" | "row_context" | null;
            condition_outcome?: components["schemas"]["ConditionOutcome"] | null;
            when_empty?: components["schemas"]["ImpliedValue"] | null;
            /**
             * @description What a value of this field's type must look like. Applied by the viewer before any formatting, compiled once and cached - a feed can have sixty million rows - and skipped rather than thrown if it will not compile, because no value may ever be blanked. Must mean the same thing in Python and JavaScript.
             * @example ^[0-9A-Fa-f]{6}$
             */
            pattern?: string | null;
            minimum?: number | null;
            maximum?: number | null;
            /** @description GTFS's own definition of the type, for when a value does not match it. */
            type_description?: string | null;
        };
        /** @description Why GTFS says this feed should not contain this file. The counterpart to `MissingFile`: that one is absent and needed, this one present and not wanted. */
        FileCondition: {
            condition: string;
            outcome: components["schemas"]["ConditionOutcome"];
        };
        /** @description A file the feed does not have and needs - required, or conditionally required with the condition holding here. Files it merely could have are not listed: a feed is normally without twenty optional files, and reporting those would bury the ones that matter. */
        MissingFile: {
            /** @example calendar */
            name: string;
            /** @enum {string} */
            presence: "required" | "conditional";
            /** @description For a conditional file, the condition in words. */
            condition?: string | null;
            condition_outcome?: components["schemas"]["ConditionOutcome"] | null;
        };
        TableInfo: {
            /** @example stops */
            name: string;
            /**
             * Format: int64
             * @example 4821
             */
            row_count: number;
            columns: components["schemas"]["ColumnInfo"][];
            forbidden?: components["schemas"]["FileCondition"] | null;
        };
        /** @description What one file cost to open. */
        FileMetrics: {
            /** @example stops.txt */
            name: string;
            /** @example stops */
            table: string;
            /**
             * Format: int64
             * @description Uncompressed size on disk.
             */
            bytes: number;
            /**
             * Format: int64
             * @description Only for a zip source; a folder has no compressed form.
             */
            compressed_bytes?: number | null;
            /** @description Declaring the view, which resolves the column list off the start of the file and reads no further - so it barely varies with size. The interface labels it "read headers". */
            register_ms: number;
            /** @description Rewriting this table as Parquet; null when it was not converted. */
            convert_ms?: number | null;
            /**
             * Format: int64
             * @description What the table occupies once converted, typically far below `bytes`.
             */
            parquet_bytes?: number | null;
            /** @description The row count. Near zero on Parquet, which carries it in the footer. */
            count_ms?: number | null;
            /** Format: int64 */
            row_count?: number | null;
            columns: number;
        };
        /**
         * @description The steps of a load, in the order they happen. A source that did not perform one of them never reports it.
         * @enum {string}
         */
        LoadPhase: "start" | "download" | "upload" | "extract" | "convert" | "summarise" | "done";
        /** @description One phase a non-server source performed, named in its own terms. */
        LoadPhaseTiming: {
            /** @example Start DuckDB */
            label: string;
            ms: number;
            /**
             * @description A detail shown beside the timing.
             * @example 412 kB fetched
             */
            note?: string;
        };
        /**
         * @description What the feed cost to open.
         *
         *     Two mutually exclusive shapes. A server load reports `kind` and the
         *     timings below it. A source that performed no server load - a browser
         *     reading Parquet over range requests never downloads, unzips or converts -
         *     reports `phases` instead and omits the rest. A zero would say the work
         *     took no time rather than that it did not happen, which is why the fields
         *     are absent rather than zeroed.
         */
        LoadMetrics: {
            /** @description Phases this source actually performed. Present only for a source that is not a server load. */
            phases?: components["schemas"]["LoadPhaseTiming"][];
            /**
             * @description How the feed reached the server. Absent for a non-server source.
             * @enum {string}
             */
            kind?: "path" | "upload" | "folder" | "download";
            /** @description Downloading or receiving the upload; null for a local path. */
            acquire_ms?: number | null;
            /** Format: int64 */
            acquire_bytes?: number | null;
            /** @description Unzipping; null when the source was already-extracted files. */
            extract_ms?: number | null;
            register_ms?: number;
            /** @description Converting to Parquet; null when it was not converted. */
            convert_ms?: number | null;
            count_ms?: number;
            /** @description The phases added together. */
            total_ms: number;
            /**
             * Format: int64
             * @description The archive's size, or the sum of the files in a folder.
             */
            total_bytes: number;
            /**
             * Format: int64
             * @description What the feed occupies to query once converted; null when it was not.
             */
            stored_bytes?: number | null;
            files: components["schemas"]["FileMetrics"][];
        };
        /** @description Where a running load has got to. The same shape reports a dataset being prepared elsewhere, which is why a host implementing that path can reuse it rather than inventing its own wording. */
        LoadProgress: {
            phase: components["schemas"]["LoadPhase"];
            /**
             * Format: int64
             * @description Progress within the current phase: **bytes** during `download`, and a count of files or tables otherwise.
             */
            done: number;
            /**
             * Format: int64
             * @description What `done` is counting towards, in the same unit, or 0 when it is not knowable in advance - a download whose response carries no Content-Length, for instance.
             */
            total: number;
            /**
             * @description The file or table being worked on; empty when there is none.
             * @example stop_times
             */
            detail: string;
            /** @description False when nothing is loading, which is an ordinary answer rather than an error. */
            running: boolean;
        };
        TablesResponse: {
            /**
             * @description What to call this feed in the header.
             * @example mdb-1210.zip
             */
            source: string;
            tables: components["schemas"]["TableInfo"][];
            /**
             * @description Files absent from this feed that GTFS says it needs. Empty for a complete feed, which is the usual case.
             * @default []
             */
            missing: components["schemas"]["MissingFile"][];
            metrics?: components["schemas"]["LoadMetrics"];
        };
        PageResponse: {
            /** @description The table's columns, in the order the rows carry them. */
            columns: string[];
            /** @description One array of values per row, aligned with `columns`. **Every value is a string or null** - the loader reads all columns as text so a feed with a malformed number still opens, and the viewer formats from the schema. A number here would be formatted as one it did not ask for. */
            rows: (string | null)[][];
            /**
             * Format: int64
             * @description Rows matching the filters, not rows on this page.
             */
            total: number;
            page: number;
            page_size: number;
        };
        ValueCount: {
            /** @description Null means the field is empty in the feed. */
            value?: string | null;
            /** Format: int64 */
            count: number;
        };
        DistinctResponse: {
            values: components["schemas"]["ValueCount"][];
        };
        /**
         * @description How a filter compares. The semantics are not obvious and a
         *     reimplementation that differs will look right and behave wrongly:
         *
         *     - `eq` / `ne` - equality. **An empty value is rewritten** to `is_empty` /
         *       `is_not_empty`, because an empty field loads as NULL and `= ''` would
         *       match nothing. Get this wrong and the "(empty)" entry in a picklist
         *       reports a count and then returns no rows.
         *     - `contains` - case-insensitive substring.
         *     - `in` - the value is a comma-separated list, trimmed, with empties
         *       dropped. If nothing remains the filter is skipped entirely.
         *     - `is_empty` / `is_not_empty` - NULL **or** the empty string, both.
         *
         *     A filter naming a column the table does not have, or an operator not
         *     listed here, is ignored rather than refused.
         * @enum {string}
         */
        FilterOperator: "eq" | "ne" | "contains" | "in" | "is_empty" | "is_not_empty";
        /** @description One condition on a column. Filters combine with AND. */
        Filter: {
            /**
             * @description Checked against the table's real columns and never interpolated into SQL.
             * @example route_id
             */
            column: string;
            op: components["schemas"]["FilterOperator"];
            /**
             * @description Absent or empty for `is_empty` and `is_not_empty`. For `in`, a comma-separated list.
             * @example R1
             */
            value?: string;
        };
        /** @description A GeoJSON geometry. Null for a feature that has none. */
        Geometry: {
            /** @example Point */
            type: string;
            /** @description Nested arrays of numbers, shaped by `type`. Coordinates are rounded to five decimal places, which is about a metre. */
            coordinates: unknown;
        };
        /** @enum {string} */
        FeatureType: "Feature";
        /** @enum {string} */
        FeatureCollectionType: "FeatureCollection";
        /** @enum {string} */
        NdjsonHeaderType: "header";
        /** @enum {string} */
        NdjsonBatchType: "batch";
        /**
         * @description A GeoJSON feature. Which properties it carries depends on the layer, and
         *     the sets are deliberately minimal - one unread property is a string per
         *     stop, and a feed has hundreds of thousands:
         *
         *     - stops: `stop_id`, `stop_name`
         *     - shapes: `shape_id`
         *     - routes: `shape_id`, `route_id`, `route_short_name`, `route_long_name`,
         *       `route_color`, `route_type`
         *     - locations: `location_id`, `stop_name`
         */
        Feature: {
            type: components["schemas"]["FeatureType"];
            geometry: components["schemas"]["Geometry"] | null;
            properties: {
                [key: string]: string;
            };
        };
        FeatureCollection: {
            type: components["schemas"]["FeatureCollectionType"];
            features: components["schemas"]["Feature"][];
        };
        /** @description The first line of a streamed layer, before any features. */
        NdjsonHeader: {
            type: components["schemas"]["NdjsonHeaderType"];
            /**
             * Format: int64
             * @description Features the whole layer will contain.
             */
            total: number;
            /** @description The thinning factor applied to this layer's geometry: every `step`-th vertex was kept. `1` means the layer is drawn exactly. Above 1 the viewer says the map was simplified, so a coarse line is never passed off as the feed's own geometry. */
            step: number;
        };
        /** @description One batch of features. Any number follow the header. */
        NdjsonBatch: {
            type: components["schemas"]["NdjsonBatchType"];
            features: components["schemas"]["Feature"][];
        };
        /**
         * @description One line of an `application/x-ndjson` layer stream: a header, then any
         *     number of batches, each a complete JSON document followed by `\n`.
         *
         *     A whole layer is far too large to wait for in one piece - a large feed is
         *     about 411 MB of GeoJSON - so it is sent as it is read and the map paints
         *     as it arrives. A reader must buffer across chunk boundaries, which fall
         *     wherever the network puts them and almost never on a newline, and should
         *     skip a line that will not parse rather than abandoning the layer.
         */
        NdjsonLine: components["schemas"]["NdjsonHeader"] | components["schemas"]["NdjsonBatch"];
        /** @description An uploaded feed. Use `file` for an archive, `files` for a folder. */
        LoadFeedUpload: {
            /**
             * Format: binary
             * @description A `.zip` archive.
             */
            file?: string;
            /** @description The `.txt` files of an extracted feed, uploaded together. */
            files?: string[];
        };
        /** @description One table of an exported dataset. */
        ManifestTable: {
            /**
             * @description The GTFS file stem - `stops` for `stops.txt`.
             * @example stops
             */
            name: string;
            /**
             * @description The Parquet file, relative to the manifest.
             * @example stops.parquet
             */
            file?: string;
            /** Format: int64 */
            rows?: number;
            columns?: number;
            /**
             * Format: int64
             * @description **Version 2**: what the source file weighed before conversion. **Version 1**: the Parquet size instead - the same key meaning two things, which is why a reader must branch on `version`.
             */
            bytes?: number | null;
            /**
             * Format: int64
             * @description The size inside the archive; null for a folder source.
             */
            compressed_bytes?: number | null;
            /** Format: int64 */
            parquet_bytes?: number;
        };
        /**
         * @description `manifest.json`, written beside a dataset's Parquet files. Not returned
         *     by any endpoint here: it is read straight from the object store by a
         *     viewer querying Parquet in the browser, and is what tells such a reader
         *     which tables exist.
         *
         *     Without it the reader has no choice but to probe every table GTFS
         *     defines - 123 range requests for a seven-table feed - so publishing one
         *     is worth the trouble.
         *
         *     Its sizes cannot be recovered after the fact: conversion deletes the
         *     CSVs, and an archive member's compressed size exists only in the
         *     archive's directory. Written last, after every Parquet file is in place,
         *     so a reader holding only the bucket URL is never told about a file that
         *     has not arrived.
         */
        DatasetManifest: {
            /**
             * @description `2` carries the sizes the load report shows. `1` carried only a table list, and meant something different by `bytes` - see `ManifestTable`.
             * @example 2
             */
            version: number;
            /** Format: date-time */
            generated_at?: string;
            /**
             * @description The version that wrote it.
             * @example 1.4.2
             */
            gtfs_garage?: string;
            source?: {
                /** @enum {string} */
                kind: "zip" | "folder" | "parquet";
                /** Format: int64 */
                bytes: number;
            };
            totals?: {
                /** Format: int64 */
                uncompressed_bytes: number;
                /** Format: int64 */
                stored_bytes: number;
            };
            tables: components["schemas"]["ManifestTable"][];
        };
    };
    responses: {
        /** @description No feed is loaded. A GTFS Garage server started without one answers this until `POST /api/load` succeeds; a host that always has a feed never returns it. */
        NoFeedLoaded: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description One `FeatureCollection` when ids were given, or the whole layer as a newline-delimited JSON stream when they were not. The two are distinguished by content type, not by a field. */
        GeoJsonLayer: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["FeatureCollection"];
                "application/x-ndjson": components["schemas"]["NdjsonLine"];
            };
        };
    };
    parameters: {
        /**
         * @description A feed's id in the workdir, as `GET /api/workspace` reports it.
         * @example montreal-gtfs-zip-7f3a91c0
         */
        feed_id_path_param: string;
        /**
         * @description The table name, which is the GTFS file stem - `stops` for `stops.txt`. `locations` is the flattened form of `locations.geojson`.
         * @example stop_times
         */
        table_path_param: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The server's settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
        };
    };
    getTables: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The feed's tables. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TablesResponse"];
                };
            };
            409: components["responses"]["NoFeedLoaded"];
        };
    };
    getTable: {
        parameters: {
            query?: {
                /** @description 1-based page number. */
                page?: number;
                /** @description Rows per page. */
                page_size?: number;
                /**
                 * @description A JSON array of `Filter` objects, URL-encoded. Empty array means no filtering. Not a repeated parameter: the value is one JSON document, because a filter is an object and query parameters are strings.
                 * @example [{"column":"route_id","op":"eq","value":"R1"}]
                 */
                filters?: string;
            };
            header?: never;
            path: {
                /**
                 * @description The table name, which is the GTFS file stem - `stops` for `stops.txt`. `locations` is the flattened form of `locations.geojson`.
                 * @example stop_times
                 */
                table: components["parameters"]["table_path_param"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse"];
                };
            };
            /** @description `filters` was not valid JSON, or was valid JSON that is not an array. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The feed has no such table. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            409: components["responses"]["NoFeedLoaded"];
        };
    };
    getDistinctValues: {
        parameters: {
            query?: {
                /** @description Most values to return. A column with more distinct values than this is truncated rather than refused. */
                limit?: number;
            };
            header?: never;
            path: {
                /**
                 * @description The table name, which is the GTFS file stem - `stops` for `stops.txt`. `locations` is the flattened form of `locations.geojson`.
                 * @example stop_times
                 */
                table: components["parameters"]["table_path_param"];
                /**
                 * @description The column to count values of.
                 * @example route_type
                 */
                column: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The values present, most frequent first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DistinctResponse"];
                };
            };
            /** @description The feed has no such table, or that table has no such column. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            409: components["responses"]["NoFeedLoaded"];
        };
    };
    getStopsGeojson: {
        parameters: {
            query?: {
                /** @description Repeat the parameter per id. Never comma-joined: a GTFS id may contain a comma, which a delimiter would split into two ids matching nothing. */
                stop_ids?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["GeoJsonLayer"];
            409: components["responses"]["NoFeedLoaded"];
        };
    };
    getShapesGeojson: {
        parameters: {
            query?: {
                /** @description Repeat the parameter per id. See `stop_ids`. */
                shape_ids?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["GeoJsonLayer"];
            409: components["responses"]["NoFeedLoaded"];
        };
    };
    getLocationsGeojson: {
        parameters: {
            query?: {
                /** @description Repeat the parameter per id. See `stop_ids`. */
                location_ids?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["GeoJsonLayer"];
            409: components["responses"]["NoFeedLoaded"];
        };
    };
    getRoutesGeojson: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The layer, as a newline-delimited JSON stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-ndjson": components["schemas"]["NdjsonLine"];
                };
            };
            409: components["responses"]["NoFeedLoaded"];
        };
    };
    getLoadProgress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current reading. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadProgress"];
                };
            };
        };
    };
    loadFeed: {
        parameters: {
            query?: {
                /** @description A path on the server's own filesystem - a `.zip` or a folder. */
                path?: string;
                /** @description A URL for the server to download. */
                url?: string;
                /** @description What to call a feed uploaded as loose files, which arrive without a container to take a name from. */
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["LoadFeedUpload"];
            };
        };
        responses: {
            /** @description The feed, described as `GET /api/tables` would describe it. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TablesResponse"];
                };
            };
            /** @description No source was supplied, or the feed could not be opened - a download that failed, an archive with no GTFS files in it. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The workdir. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceResponse"];
                };
            };
        };
    };
    clearWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The workdir, as it now stands. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceResponse"];
                };
            };
        };
    };
    removeWorkspaceFeed: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description A feed's id in the workdir, as `GET /api/workspace` reports it.
                 * @example montreal-gtfs-zip-7f3a91c0
                 */
                feed_id: components["parameters"]["feed_id_path_param"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The workdir, as it now stands. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceResponse"];
                };
            };
            /** @description No such feed in the workdir. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description That feed is open, so its files cannot be removed. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    reloadWorkspaceFeed: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description A feed's id in the workdir, as `GET /api/workspace` reports it.
                 * @example montreal-gtfs-zip-7f3a91c0
                 */
                feed_id: components["parameters"]["feed_id_path_param"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The feed, described as `GET /api/tables` would describe it. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TablesResponse"];
                };
            };
            /** @description No such feed in the workdir, or one with no Parquet to reopen - a feed loaded with `--no-parquet`, or a load that was interrupted. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
